#!/usr/bin/env bash

# Tool versions
NODE_VERSION="${NODE_VERSION:-24.12.0}"
GO_VERSION="${GO_VERSION:-1.25.5}"
JAVA_MAJOR="${JAVA_MAJOR:-21}"
DOTNET_VERSION="${DOTNET_VERSION:-10.0}"
LEAN_VERSION="${LEAN_VERSION:v4.13.0}"

# Paths
GO_INSTALL_DIR="/usr/local/go"